---
title: "IDR4000: Hjemmelekse uke 50"
format:
  typst:
    columns: 1
editor_options: 
  chunk_output_type: console
---


Forbered deg på å diskutere spørsmålene under i timen i uke 49. 

::: {.block fill="luma(230)" inset="8pt" radius="4pt"}

IQ måles ofte på en standardisert skale hvor verdier i populasjonen indikerer et gjennomsnitt på 100 og et standardavvik på 15. Du skal gjennomføre en studie som ønsker å teste hypotesen at sjakkspillere har en høyere IQ sammenlignet med den gjennomsnittlige befolkningen.

:::


1. Hvordan kan vi formulere en null-hypotese for problemstillingen over og hvilken statistisk test er passende for problemet?
2. Hva tilsvarer en effektstørrelse på 0.5 og 1 i denne sammenhengen?
3. Hvor mange sjakkspillere trenger vi for å oppnå en statistisk styrke på 90% for en effektstørrelse på 0.5 og 1, gitt en feilrate for Type 1-feil på 5%?
4. Hvordan kan man resonere om Type 1 og Type 2 feil i denne sammenhengen?




```{r}
#| echo: false
#| message: false
#| warning: false

set.seed(1)

a <- rnorm(28, 0, 1)
b <- rnorm(18, 0.6,1 )

res <- t.test(a, b)



a_text <- paste0(round(mean(a),2), " (SD: ", round(sd(a), 2), "), n = ", length(a))
b_text <- paste0(round(mean(b),2), " (", round(sd(b), 2), "), n = ", length(b))


test_text <- paste0(round(res$estimate[2] - res$estimate[1], 2), 
                    ", 95% CI: [",
                    round(-res$conf.int[2], 2),
                    ", ",
                    round(-res$conf.int[1], 2),
                    "], t(",
                    round(res$parameter, 1), 
                    ")", 
                    " = ", 
                    round(-res$statistic, 2),
                    ", p = ", 
                    
                    round(res$p.value, 3)
                    )
                    



```

::: {.block fill="luma(230)" inset="8pt" radius="4pt"}
La oss si at du har gjennomført et forskningsprosjekt, to grupper trener i tolv uker og den relative forandringen fra pre til post (post/pre - 1) sammenlignes med et uavhengig t-test. Gjennomsnitt i gruppe A er `r a_text`, gjennomsnitt i gruppe B er `r b_text` og forskjellen mellom gruppene estimeres til `r test_text`.
:::

5. Hva betyr p-verdien? Sett et kryss når en påstand er SANN


```{=typst}
#import "@preview/cheq:0.3.0": checklist
#show: checklist

- [ ] 1. Du har bevist at nullhypotesen ikke er sann. 
- [ ] 2. Du har fått frem sannsynligheten for at nullhypotesen er sann.
- [ ] 3. Du har bevist den eksperimentelle (alternative) hypotesen. 
- [ ] 4. Du kan konkludere om sannsynligheten for at den alternative hypotesen er sann.
- [ ] 5. Du vet, hvis du forkaster nullhypotesen, sannsynligheten at du tar feil beslutt. 
- [ ] 6. Du har et reliabelt eksperimentelt funn i mening at, hvis du gjør eksperimentet igjen, så vil du få samme resultat 1-p% av tilfellene.  

```


::: {.block fill="luma(230)" inset="8pt" radius="4pt"}

I klassisk statistikk så beregnes den kondisjonale sannsynligheten *p*(D|H~0~). Vi kan lese dette som sannsynligheten (*p*) for dataene som vi har observert (D), gitt nullhypotesen (H~0~). Er dette sannsynligheten du ønsker å vite når du gjennomfører en studie? 
:::



