---
title: "IDR4000: Hjemmelekse uke 35"
format:
  typst:
    columns: 1
---

Forbered deg på å diskutere spørsmålene under i timen i uke 35.


1. En variabel har blitt målt i laboratoriet, laveste mulige resultat er 0, avstanden mellom 1 og 2 er det samme som mellom 3 og 4. Hva kaller vi variabelen?
2. En variabel som kan brukes for å skille to kategorier uten naturlig rekkefølge kalles?
3. Maksimal styrke i benbøj er en variabel som vi kan beskrive som ...?
4. Hva kjennetegner et «tidy» datasett?
5. Hva er «missing data», hvordan kan vi håndtere disse i datasett?
6. Hva skiller gjennomsnittet fra medianen? 
7. I en variabel er gjennomsnittet 70, men medianen er bare 12. Hva sier dette om hvordan variabelen er fordelt? 
8. Beskriv prinsippet for hvordan standardavviket beregnes. 
9. Beskriv prinsippet for hvordan variansen i en variabel beregnes.
10. Bruk datasettet `strengthvolume`, sammenstill gjennomsnitt og standardavvik for maksimal styrke i legext og legpress for hvert tidspunkt, sets og sex.
11. Hva kjennetegner en scatter plot?
12. Hva er et histogram?
13. Når bruker vi en line plot?
14. Hva kjennetegner en normalfordeling? 
15. Hva kjennetegner en binominalfordeling?
16. Hva kjennetegner en Poissonfordeling?


### Øvelser

17. Bruk datasettet `strengthvolume`og lag en graf over maksimalstyrke ved tidspunktene `session1` og `post`. Bruk en øvelse (exercise) og differensiere mellom treningsvolum (sets)
18. Bruk datasettet`strengthvolume` og lag en graf som beskriver forhold mellom bevegelshastighet og styrke. Bevegelshastighet finnes i variabelen exercise, hvor isom er isometrisk styrke (0 grader/sek), isok.60, isok.120 og isok.240 er isokinetisk styrke ved 60, 120 og 240 grader per sekund. Undersøk om vi visuelt kan forskjell mellom i forhold mellom hastighet og kraft per tidspunkt og kjønn. Her kan man bruke en statistisk modell, for eksempel i JASPs Plot Builder, eller ved å bruke `geom_smooth`i `ggplot2`. Her må variablene forandres for å lage en kontinuerlig variabel som beskriver hastighet fra den kategoriske dataen i exercise.
19. Bruk datasettet millward for å visualisere fordelingen av variabelene RNA og protein synthesis. Hvordan er variablene fordelt, hvordan kan vi beskrive fordelingene? Gjør det samme med valgfri data fra strengthvolume. 

## Læringsressurser, utover pensum:

- [Her](https://www.youtube.com/@davidpillow8987/videos) finner dere en serie med videoer som beskriver JASP (inkludert plot builder). Søk deg frem til "Lesson 1".
- Datasettene finnes i exscidata-pakken (R) og på websiden til [emnenotatene](https://dhammarstrom.github.io/quant-methods/). 
