---
title: "IDR4000: Hjemmelekse uke 44"
format:
  typst:
    columns: 1
editor_options: 
  chunk_output_type: console
---


Forbered deg på å diskutere spørsmålene under i timen i uke 44.

For problem 1-6, bruk data fra Boston maraton, år 2012 [boston2012](https://dhammarstrom.github.io/quant-methods/data-out/boston2012.csv). Hvis du bruker R så kan koden under brukes for å filtrere data og lage variabelen `speed`, som tilsvarer hastighet (km/tim).

```{r}
#| echo: true
#| eval: false

library(tidyverse)

dat <- exscidata::boston |> 
      filter(year == 2012) |> 
      mutate(speed = 42 / (seconds / 60 / 60 ))
 

```

1. Hva er gjennomsnittlig hastighet i modellen under når vi setter alder til 45?

$$
\begin{align}
y_i &\sim \operatorname{Normal}(\mu_i, \sigma) \\
\mu_i &= \beta_0 + \beta_1 \times \text{age}_i + \beta_2 \times \text{age}_i^2
\end{align}
$$ 
2. Legg til kjønn (gender) til modellen (uten interaksjonseffekt), hva er forskjellen i hastighet mellom menn og kvinner?

3. Beskriv modellen over med matematisk notasjon, lignende den som beskriver Model 1.

4. Bygg om modellen så den tillater interaksjon mellom kjønn og alder (age og age^2). Hva er forskjellen mellom menn og kvinner i hastighet når alder er 18, 40, 60, og 85?

5. Beskriv modellen over i matematisk notasjon.

6. Lag en residual-plot for din modell. Sett predikerte verdier på x-aksel og residualene på y-aksel. Hva forteller figurene deg om antagelsene om modellen?


For problem 7-12, bruk data på fotballskader [injury](https://dhammarstrom.github.io/quant-methods/data-out/injury.csv). Hvis du bruker R så finner du datasettet i `exscidata::injury`, du må installere pakken på nytt. Utfallsvariabelen er `Injury_Next_Season`.


7. Hva er log-odds ratio mellom de som gjennomfører oppvarming (`Warmup_Routine_Adherence == 1`) sammenlignet med de som ikke gjør det (`Warmup_Routine_Adherence == 0`).  Bruk modellen beskrevet under.


$$
\begin{align}
y_i &\sim \operatorname{Binomial}(1, p_i) \\
\operatorname{log}\left(\frac{p_i}{1-p_i} \right)&= \beta_0 + \beta_1 \times \text{W}_i \\
W&: \text{Warmup_Routine_Adherence}
\end{align}
$$ 

8. Hva er odds ratioen for den samme sammenligningen?

9. Hva er oddsen for skade hos de som gjennomfør oppvarming (`Warmup_Routine_Adherence == 1`) og hos de som ikke gjør det (`Warmup_Routine_Adherence == 0`)?

10. Legg til `Hamstring_Flexibility` som uavhengig variabel i modellen og beskriv den med matematisk notasjon.

11. Hva er odds for skade hos en fotballspiller med hamstring bevegelseskår på 80?

12. Bruk den samme modellen, hva er odds-ratioen for skade mellom en spiller med hamstring bevegelseskår på 87 sammenlignet med bevegelseskår på 73?


